-- nvim-navic

require("nvim-navic").setup({
	icons = {
		Method = " ",
		File = " ",
		Module = "󰕳 ",
		Namespace = "󰌗 ",
		Package = " ",
		Class = " ",
		Property = " ",
		Field = " ",
		Constructor = " ",
		Enum = " ",
		Interface = " ",
		Function = "󰡱 ",
		Variable = " ",
		Constant = " ",
		String = " ",
		Number = " ",
		Boolean = " ",
		Array = "󰅨 ",
		Object = " ",
		Key = " ",
		Null = "󰟢 ",
		EnumMember = " ",
		Struct = " ",
		Event = " ",
		Operator = " ",
		TypeParameter = " ",
	},
})
