# Shared environment variables.
source ~/.shared_shell.sh

# Enable history appending instead of overwriting.
shopt -s histappend

export HISTFILE="${XDG_STATE_HOME}/bash/history"

# fzf
source /usr/share/fzf/completion.bash
source /usr/share/fzf/key-bindings.bash
