#!/usr/bin/dash
# Script to start the screen locker.
set -e

XSECURELOCK_AUTH_TIMEOUT=30 \
XSECURELOCK_BLANK_TIMEOUT=10 \
XSECURELOCK_BLANK_DPMS_STATE=off \
XSECURELOCK_BURNIN_MITIGATION=100 \
XSECURELOCK_BURNIN_MITIGATION_DYNAMIC=1 \
XSECURELOCK_DATETIME_FORMAT="%A %b %d-%m-%Y    %T" \
XSECURELOCK_FONT="Ubuntu Nerd Font Medium" \
XSECURELOCK_PASSWORD_PROMPT=emoticon \
XSECURELOCK_SAVER=~/scripts/saver_sleep_after_time \
XSECURELOCK_SHOW_DATETIME=1 \
XSECURELOCK_SHOW_HOSTNAME=0 \
XSECURELOCK_SHOW_USERNAME=0 xsecurelock
